### ISSUE TITLE
Resources without DynamoDB

### ISSUE THREAD

**Issue by Linus-Boehm** [crolly/mug#5]
Basically not generating the Dynamo part in the serverless.yml if no attributes are specified  in the mug.config. Usefull for communicating with external APIs like Cognito

**Comment by crolly** [comment]
Can you provide some additional information on what you mean by no attributes are specified? What would the point of using mug be?

**Comment by crolly** [comment]
You can now add function groups which basically are just a collection of functions without a resource being defined. Please see the documentation for further details.
