### ISSUE TITLE
[sls-function-level] Adding Resource causes ne generation of all sls.ymls

### ISSUE THREAD

**Issue by Linus-Boehm** [crolly/mug#6]
By adding a new resource all serverless.ymls are newly generated and custom changes are reverted.

Expected:
Only new Ressource YML is generated

**Comment by crolly** [comment]
fixed with [latest commit](https://github.com/crolly/mug/commit/2c1bb11b6d99cca450bbb4a88b1b41de462a5ab8). you can now e.g. run `mug add resource course -a "name" -i` in order to not regenerate previous ymls.
I'm thinking about implementing `-i` feature as default.
